server:
  port: 9000

spring:
  application:
    name: auth
  sql:
    init:
      mode: always
      schema-locations: classpath:dev/db/schema.sql
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/authdb?allowPublicKeyRetrieval=true&sslMode=DISABLED}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_USER_PASSWORD:123456789}
    driver-class-name: com.mysql.cj.jdbc.Driver

domain:
  control:
    name: ${DOMAIN_CONTROL_NAME:benzaquem.com.br}
    url: ${DOMAIN_CONTROL_URL:ldap://192.168.153.132:389/}

logging:
  level:
    org.springframework.security: DEBUG
