server:
  port: ${SERVER_PORT:9000}

spring:
  application:
    name: auth
  sql:
    init:
      mode: always
      schema-locations: classpath:dev/db/schema.sql
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/authdb?allowPublicKeyRetrieval=true&sslMode=DISABLED}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_USER_PASSWORD:123456789}
    driver-class-name: com.mysql.cj.jdbc.Driver

domain:
  control:
    name: ${DOMAIN_CONTROL_NAME:benzaquem.com.br}
    url: ${DOMAIN_CONTROL_URL:ldap://192.168.153.132:389/}

sipe:
  api:
    url: ${SIPE_API_URL:http://localhost:8084}
  web:
    url: ${SIPE_WEB_URL:http://localhost:4200}

jsarh:
  api:
    url: ${JSARH_URL:http://localhost:8087}

coletor:
  api:
    url: ${COLETOR_URL:http://localhost:8082}

logging:
  level:
    org.springframework.security: DEBUG
