server:
  port: 9000

spring:
  application:
    name: auth
  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa123456
    driver-class-name: org.h2.Driver

domain:
  control:
    name: ${DOMAIN_CONTROL_NAME}
    url: ${DOMAIN_CONTROL_URL}

logging:
  level:
    org.springframework.security: INFO
